settings:
  import/extensions:
    - '.js'
    - '.jsx'
    - '.ts'
    - '.tsx'
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
      paths:
        - 'src'
env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
    ecmaVersion: latest
    sourceType: module
parser: '@typescript-eslint/parser'
plugins:
  - react
  - react-hooks
  - import
rules:
  no-underscore-dangle: ['error', { allowAfterThis: true }]
  import/prefer-default-export: 'off'
  react/prop-types: 'off'
  no-confusing-arrow: 'off'
  react/react-in-jsx-scope: 'off'
  template-curly-spacing: 'off'
  #max-len: ["warn", {code: 120}]
  max-len: 'off'
  indent: ['error', 2, { ignoredNodes: ['TemplateLiteral', 'JSX'] }]
  react/jsx-indent: ['warn', 2]
  react/jsx-indent-props: ['error', 2]
  react/jsx-filename-extension:
    #- 1
    - 0
    - extensions:
        - '.ts'
        - '.tsx'
  react/jsx-first-prop-new-line: [1, 'multiline']
  react/jsx-max-props-per-line:
    - 2
    - maximum: 3
      when: always
  no-console:
    - off
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'warn'
  react/jsx-props-no-spreading: [0]
  react/jsx-curly-brace-presence: 'warn'
  react/jsx-no-useless-fragment:
    - error
    - allowExpressions: true
  react/function-component-definition:
    - 1
    - namedComponents: 'arrow-function'
      unnamedComponents: 'arrow-function'
  react/no-unused-prop-types:
    - 1
    - ignore: ['theme']
  react/require-default-props:
    - off
  require-await: 'error'
  linebreak-style: 'off'
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/named: 'off'
  space-infix-ops: 'off'
  no-undef: 'off'
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  import/no-unresolved: [1, { caseSensitive: false }]
  import/no-extraneous-dependencies:
    - off
  import/no-cycle:
    - warn
  no-unused-vars:
    - off
    - args: 'none'
  no-unused-expressions:
    - warn
    - allowShortCircuit: true
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/no-empty-function': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  # DO NOT FORGET TO ON
  '@typescript-eslint/no-explicit-any': 'off'
  class-methods-use-this:
    - warn
  no-restricted-exports:
    - warn
  no-shadow: 'off'
  '@typescript-eslint/no-shadow': 'error'
  arrow-body-style:
    - warn
  semi:
    - warn
    - never

ignorePatterns:
  - '**/generated/*'
  - '!**/src/*'
  - '**/assets/*'
  - '**/__mocks__/*'
  - '**/build/*'
  - 'fonts.css'
  - '*.woff2'
  - '*.otf'
  - '*.jpg'
  - '*.png'
  - '*.svg'
  - '*.csv'
  - '*.avif'
  - '*.webp'
  - '*.scss'
  - '*.json'
